name: floating_palette_workspace

packages:
  - floating_palette_annotations
  - floating_palette_generator
  - floating_palette

command:
  version:
    message: "chore: release {versioning}"
  bootstrap:
    usePubspecOverrides: true
