builders:
  floating_palette_generator:
    import: "package:floating_palette_generator/floating_palette_generator.dart"
    builder_factories: ["paletteBuilder"]
    build_extensions: {".dart": [".floating_palette.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]
